// <auto-generated />
using System;
using ArzenalStoreInfrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arzenal.Store.Api.Infrastructure.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Arzenal.Store.Api.Domain.Models.App", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<long>("AppSize")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icone")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ReleaseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Apps", (string)null);
                });

            modelBuilder.Entity("Arzenal.Store.Api.Domain.Models.AppLanguage", b =>
                {
                    b.Property<Guid>("AppId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.HasKey("AppId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("AppLanguages", (string)null);
                });

            modelBuilder.Entity("Arzenal.Store.Api.Domain.Models.AppOperatingSystem", b =>
                {
                    b.Property<Guid>("AppId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OSId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.HasKey("AppId", "OSId");

                    b.HasIndex("OSId");

                    b.ToTable("AppOperatingSystems", (string)null);
                });

            modelBuilder.Entity("Arzenal.Store.Api.Domain.Models.AppTag", b =>
                {
                    b.Property<Guid>("AppId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TagId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.HasKey("AppId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("AppTags", (string)null);
                });

            modelBuilder.Entity("Arzenal.Store.Api.Domain.Models.Categorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Arzenal.Store.Api.Domain.Models.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("Arzenal.Store.Api.Domain.Models.OperatingSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OperatingSystems", (string)null);
                });

            modelBuilder.Entity("Arzenal.Store.Api.Domain.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("Arzenal.Store.Api.Domain.Models.App", b =>
                {
                    b.HasOne("Arzenal.Store.Api.Domain.Models.Categorie", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Arzenal.Store.Api.Domain.Models.AppLanguage", b =>
                {
                    b.HasOne("Arzenal.Store.Api.Domain.Models.App", "App")
                        .WithMany("AppLanguages")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arzenal.Store.Api.Domain.Models.Language", "Language")
                        .WithMany("AppLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Arzenal.Store.Api.Domain.Models.AppOperatingSystem", b =>
                {
                    b.HasOne("Arzenal.Store.Api.Domain.Models.App", "App")
                        .WithMany("AppOperatingSystems")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arzenal.Store.Api.Domain.Models.OperatingSystem", "OperatingSystem")
                        .WithMany("AppOperatingSystems")
                        .HasForeignKey("OSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("OperatingSystem");
                });

            modelBuilder.Entity("Arzenal.Store.Api.Domain.Models.AppTag", b =>
                {
                    b.HasOne("Arzenal.Store.Api.Domain.Models.App", "App")
                        .WithMany("AppTags")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arzenal.Store.Api.Domain.Models.Tag", "Tag")
                        .WithMany("AppTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Arzenal.Store.Api.Domain.Models.App", b =>
                {
                    b.Navigation("AppLanguages");

                    b.Navigation("AppOperatingSystems");

                    b.Navigation("AppTags");
                });

            modelBuilder.Entity("Arzenal.Store.Api.Domain.Models.Language", b =>
                {
                    b.Navigation("AppLanguages");
                });

            modelBuilder.Entity("Arzenal.Store.Api.Domain.Models.OperatingSystem", b =>
                {
                    b.Navigation("AppOperatingSystems");
                });

            modelBuilder.Entity("Arzenal.Store.Api.Domain.Models.Tag", b =>
                {
                    b.Navigation("AppTags");
                });
#pragma warning restore 612, 618
        }
    }
}
